version: '3.9'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1234@Abcd"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  employeedeactivation:
    build: .
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"
    